apiVersion: api.vmsp.vmware.com/v1alpha1
kind: Component
metadata:
  creationTimestamp: "2026-09-17T01:16:18Z"
  finalizers:
  - component.vmsp.vmware.com/finalizer
  generation: 1
  labels:
    component.vmsp.vmware.com/id: 38eb20b2-85f2-3b51-a6b1-5115cc7f671f
    component.vmsp.vmware.com/name: vcfa
    component.vmsp.vmware.com/type: vcfa
    component.vmsp.vmware.com/version: 8.0.0
  name: vcfa
  resourceVersion: "19718662"
  uid: 23c79045-2d56-4667-af62-a3bf0b7f34ef
spec:
  id: 38eb20b2-85f2-3b51-a6b1-5115cc7f671f
  namespace: prelude
  size: medium
  versionRef:
    name: vcfa-8.0.0
status:
  namespace: prelude
  phase: Unknown
